GET http://localhost:4000/api/bank/bank

###

GET http://localhost:4000/api/users/test

###

GET http://localhost:4000/api/users/login/test@test.com/12345678

###

POST http://localhost:4000/api/users/createUser
Content-Type: application/json

{
    "name": "lala",
    "email": "test3@test.com",
    "password": "12345678"
}

###
GET http://localhost:4000/api/users/getAllUsers

###

GET http://localhost:4000/api/users/getAllAction/6196698b890628d4d09b59b3